name: Notify IndexNow on push

on:
  push:
    branches: [ main ]          # 你的默认分支

jobs:
  submit-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Submit sitemap URL to IndexNow
        env:
          INDEXNOW_KEY: "DDCB9376C9FC9075B0E18873C8B0D1FE"   # 改为你自己的密钥
        run: |
          curl "https://api.indexnow.org/indexnow?url=https://facedriverpins.github.io/sitemap.xml&key=${INDEXNOW_KEY}"
